name: Deploy to Railway

on:
  push:
    branches:
      - main # Trigger on pushes to your main branch (adjust if your main branch is named differently, e.g., 'master')

env:
  # Base name for your Docker image. Replaced by your GitHub username/repo
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to GitHub Container Registry (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        # Authenticates with GHCR using your GitHub token
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is a built-in secret

      - name: Extract metadata (tags, labels) for Docker
        # Generates Docker tags like 'latest' and commit SHA for your image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}} # Tag 'latest' on your default branch (main/master)
            type=sha,format=long # Also tag with the long commit SHA

      - name: Build and push Docker image
        # Builds your Dockerfile and pushes the image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: . # Assumes your Dockerfile is in the root of your repo
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to Railway
        # Uses the Railway CLI Docker image to trigger the deployment
        # The 'railway up' command will detect your already configured service
        # and pull the latest image from GHCR (specified by your repo/tag)
        uses: docker/run-action@v1 # Action to run a Docker container
        with:
          image: ghcr.io/railwayapp/cli:latest # The official Railway CLI Docker image
          options: > # Pass environment variables to the container
            --env RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}
            --env RAILWAY_SERVICE_ID=${{ secrets.RAILWAY_SERVICE_ID }} # Use this if you configured the secret
          run: railway up # The command to execute inside the Railway CLI container